/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BotSpend {
  export type AgentProfileStruct = {
    wallet: AddressLike;
    name: string;
    description: string;
    registeredAt: BigNumberish;
    isActive: boolean;
  };

  export type AgentProfileStructOutput = [
    wallet: string,
    name: string,
    description: string,
    registeredAt: bigint,
    isActive: boolean
  ] & {
    wallet: string;
    name: string;
    description: string;
    registeredAt: bigint;
    isActive: boolean;
  };

  export type PaymentRecordStruct = {
    from: AddressLike;
    to: AddressLike;
    amount: BigNumberish;
    note: string;
    timestamp: BigNumberish;
  };

  export type PaymentRecordStructOutput = [
    from: string,
    to: string,
    amount: bigint,
    note: string,
    timestamp: bigint
  ] & {
    from: string;
    to: string;
    amount: bigint;
    note: string;
    timestamp: bigint;
  };

  export type ServiceRequestStruct = {
    id: BigNumberish;
    requester: AddressLike;
    provider: AddressLike;
    description: string;
    amount: BigNumberish;
    completed: boolean;
    createdAt: BigNumberish;
  };

  export type ServiceRequestStructOutput = [
    id: bigint,
    requester: string,
    provider: string,
    description: string,
    amount: bigint,
    completed: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    requester: string;
    provider: string;
    description: string;
    amount: bigint;
    completed: boolean;
    createdAt: bigint;
  };
}

export interface BotSpendInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeServiceRequest"
      | "createServiceRequest"
      | "getAgent"
      | "getAgentByWallet"
      | "getAgentCount"
      | "getPayment"
      | "getPaymentCount"
      | "getRequest"
      | "getRequestCount"
      | "getRequesterRequests"
      | "payAgent"
      | "registerAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "PaymentSent"
      | "ServiceRequestCompleted"
      | "ServiceRequestCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeServiceRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createServiceRequest",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentByWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequesterRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payAgent",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "completeServiceRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createServiceRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequesterRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    name: string,
    description: string,
    registeredAt: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    name: string,
    description: string,
    registeredAt: bigint
  ];
  export interface OutputObject {
    wallet: string;
    name: string;
    description: string;
    registeredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSentEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    note: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    note: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    note: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceRequestCompletedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    provider: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    provider: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    provider: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceRequestCreatedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    provider: AddressLike,
    description: string,
    amount: BigNumberish,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    provider: string,
    description: string,
    amount: bigint,
    createdAt: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    provider: string;
    description: string;
    amount: bigint;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BotSpend extends BaseContract {
  connect(runner?: ContractRunner | null): BotSpend;
  waitForDeployment(): Promise<this>;

  interface: BotSpendInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeServiceRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createServiceRequest: TypedContractMethod<
    [provider: AddressLike, description: string, amount: BigNumberish],
    [bigint],
    "payable"
  >;

  getAgent: TypedContractMethod<
    [index: BigNumberish],
    [BotSpend.AgentProfileStructOutput],
    "view"
  >;

  getAgentByWallet: TypedContractMethod<
    [wallet: AddressLike],
    [BotSpend.AgentProfileStructOutput],
    "view"
  >;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  getPayment: TypedContractMethod<
    [index: BigNumberish],
    [BotSpend.PaymentRecordStructOutput],
    "view"
  >;

  getPaymentCount: TypedContractMethod<[], [bigint], "view">;

  getRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [BotSpend.ServiceRequestStructOutput],
    "view"
  >;

  getRequestCount: TypedContractMethod<[], [bigint], "view">;

  getRequesterRequests: TypedContractMethod<
    [requester: AddressLike],
    [bigint[]],
    "view"
  >;

  payAgent: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, note: string],
    [void],
    "payable"
  >;

  registerAgent: TypedContractMethod<
    [name: string, description: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeServiceRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createServiceRequest"
  ): TypedContractMethod<
    [provider: AddressLike, description: string, amount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [index: BigNumberish],
    [BotSpend.AgentProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByWallet"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [BotSpend.AgentProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [index: BigNumberish],
    [BotSpend.PaymentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [BotSpend.ServiceRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequesterRequests"
  ): TypedContractMethod<[requester: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "payAgent"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, note: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, description: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSent"
  ): TypedContractEvent<
    PaymentSentEvent.InputTuple,
    PaymentSentEvent.OutputTuple,
    PaymentSentEvent.OutputObject
  >;
  getEvent(
    key: "ServiceRequestCompleted"
  ): TypedContractEvent<
    ServiceRequestCompletedEvent.InputTuple,
    ServiceRequestCompletedEvent.OutputTuple,
    ServiceRequestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceRequestCreated"
  ): TypedContractEvent<
    ServiceRequestCreatedEvent.InputTuple,
    ServiceRequestCreatedEvent.OutputTuple,
    ServiceRequestCreatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string,string,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "PaymentSent(address,address,uint256,string,uint256)": TypedContractEvent<
      PaymentSentEvent.InputTuple,
      PaymentSentEvent.OutputTuple,
      PaymentSentEvent.OutputObject
    >;
    PaymentSent: TypedContractEvent<
      PaymentSentEvent.InputTuple,
      PaymentSentEvent.OutputTuple,
      PaymentSentEvent.OutputObject
    >;

    "ServiceRequestCompleted(uint256,address,uint256)": TypedContractEvent<
      ServiceRequestCompletedEvent.InputTuple,
      ServiceRequestCompletedEvent.OutputTuple,
      ServiceRequestCompletedEvent.OutputObject
    >;
    ServiceRequestCompleted: TypedContractEvent<
      ServiceRequestCompletedEvent.InputTuple,
      ServiceRequestCompletedEvent.OutputTuple,
      ServiceRequestCompletedEvent.OutputObject
    >;

    "ServiceRequestCreated(uint256,address,address,string,uint256,uint256)": TypedContractEvent<
      ServiceRequestCreatedEvent.InputTuple,
      ServiceRequestCreatedEvent.OutputTuple,
      ServiceRequestCreatedEvent.OutputObject
    >;
    ServiceRequestCreated: TypedContractEvent<
      ServiceRequestCreatedEvent.InputTuple,
      ServiceRequestCreatedEvent.OutputTuple,
      ServiceRequestCreatedEvent.OutputObject
    >;
  };
}
