/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BotSpend } from "./BotSpend";
export * as factories from "./factories";
export { BotSpend__factory } from "./factories/BotSpend__factory";
